title: "Duong Nguyen"
description: "Data & Business Analysis Portfolio"
avatar: "/assets/img/avatar.jpg"

author:
  name: "Duong Nguyen"
  email: "ntnguyenduong0208@gmail.com"
  linkedin: "https://www.linkedin.com/in/thuy-duong-nguyen-4289a7285/"
  
